### ISSUE TITLE
Refactor code base and improve greeting 

### ISSUE THREAD

**Issue by kzisme** [Progether/IRC-Bot#54]
@paddatrapper and I noticed a few improvements that could be made to keep users connected long or to even make them feel more welcome as they join irc.  

Also when glancing at the source I see many comments about things that can be fixed.

**Comment by paddatrapper** [comment]
Namely the improvements were:
- [x] Including a notice about slow responses from the channel because of the nature of IRC
- [x] Perhaps a link to an "IRC how-to" as most people joining the channel are new to IRC in general

**Comment by kzisme** [comment]
:D I agree with both of those sentiments and I'm sure more ideas will come up when we begin working!

**Comment by paddatrapper** [comment]
Any idea as to what site to link to about IRC? My suggestions would be one of the following:

* [IRC Help](http://www.irchelp.org/)
* [Wikipedia](https://en.wikipedia.org/wiki/Internet_Relay_Chat)
* [IRC Beginner](http://www.ircbeginner.com/index.php)

**Comment by kzisme** [comment]
@paddatrapper I like [this](http://www.irchelp.org/irchelp/new2irc.html) link the best - it's more to the point and a little ~less~ overwhelming.

Do you approve?

**Comment by paddatrapper** [comment]
A much better link, though it doesn't mention weechat as a client!

**Comment by kzisme** [comment]
It's hard to cover all the bases with clients - but I feel it gives a nice overview for ~most~ people ( a starting point if you will)

In the future we may be able to create/write our own IRC help section on progether.com (unless its' defunct), or into the progether wiki.

**Comment by paddatrapper** [comment]
Yeah, it was more of a joke than anything else. I'm reluctant for us to
maintain yet another thing when there are plenty of good sites (like the
one you suggested) already out there

**Comment by kzisme** [comment]
Oh!  I thought you were a huge proponent for WeeChat or something - yeah I'm not into the idea of maintaining something like that either :D

**Comment by paddatrapper** [comment]
Nah, I simply use it and like how it works

**Comment by kzisme** [comment]
Ah :) I mistook what you said - I thought you were being serious

**Comment by paddatrapper** [comment]
No worries. The joys of text based communication...

**Comment by paddatrapper** [comment]
Welcome message has been updated and merged. Now what is left is the code base refactoring

**Comment by kzisme** [comment]
I'm going to close this issue and open a new one for refactoring based off of the comments in the source
